#!/bin/sh
#
# pnetaudio - Portable Networked Audio
#
# Copyright 2011 Thomas de Grivel <billitch@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# openbsd/pnetaudioc - TCP audio client for openbsd
#

usage() {
    echo "Usage: env [PORT=...] [DEVICE=...] $0 HOST" >&2
    exit 1
}

test $# -gt 0 || usage

HOST=$1
PORT=${PORT:-9636}
FRAMES=${FRAMES:-1152}
BUFFER=${BUFFER:-4096}
DEVICE=${DEVICE:-default}

if ! ping -c 1 -w 1 $HOST >/dev/null 2>&1; then
    echo "$0: Invalid host: $HOST" >&2
    exit 2
fi

while sleep 1; do
    echo "$0: sending to ${HOST}:${PORT} $FRAMES frames $BUFFER bytes" >&2
    aucat -s ${DEVICE} -m mon -b $FRAMES -e s16le -h raw -r 44100 -o - | \
        flac -sc0b $FRAMES --endian=little --channels=2 --bps=16 --sample-rate=44100 --sign=signed - | \
        nc -O $BUFFER $HOST $PORT
done
