#!/bin/sh
#
# pnetaudio - Portable Networked Audio
#
# Copyright 2011 Thomas de Grivel <billitch@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# openbsd/pnetaudiod - TCP audio daemon for openbsd
#

IP=${IP:-0.0.0.0}
PORT=${PORT:-9636}
FRAMES=${FRAMES:-1024}
BUFFER=${BUFFER:-2048}

while sleep 1; do
    echo "$0: listening on ${IP}:${PORT} $FRAMES frames $BUFFER bytes" >&2
    nc -dlI $BUFFER $IP $PORT | \
	flac -scdb $FRAMES - | \
	aucat -i - -m play -b $FRAMES
done
